#!/usr/bin/env python3
"""
Derive the mapping between the replay CSV and the model's input space.

public/data/secom_cleaned_dataset.csv holds all 590 SECOM columns, imputed and
min-max normalized to [0, 1]. The autoencoder was trained on the 558 columns
that survived cleaning, in raw sensor units, and its StandardScaler expects
those units. This script recovers both halves of that mapping from the original
UCI SECOM release:

  * kept columns  = columns whose missing-value fraction is <= MAX_MISSING_FRACTION
  * raw value     = normalized * (max - min) + min   (per column, from the raw file)

The result is written as a TypeScript module consumed by src/lib/feature-adapter.ts.
Re-run it only if the replay dataset or the trained model changes.

Usage:
    python scripts/export_feature_space.py                    # downloads secom.zip
    python scripts/export_feature_space.py --secom-data path/to/secom.data
"""

from __future__ import annotations

import argparse
import io
import json
import urllib.request
import zipfile
from pathlib import Path

import numpy as np

SECOM_URL = "https://archive.ics.uci.edu/static/public/179/secom.zip"
MAX_MISSING_FRACTION = 0.2
DEFAULT_OUTPUT = Path(__file__).resolve().parents[1] / "src" / "lib" / "model" / "feature-space.ts"
DEFAULT_SCALER = (
    Path(__file__).resolve().parents[2]
    / "secom_failure_prediction"
    / "training"
    / "scaler_params.json"
)


def load_raw(secom_data: Path | None) -> np.ndarray:
    if secom_data is not None:
        return np.genfromtxt(secom_data, delimiter=" ")

    print(f"Downloading {SECOM_URL} …")
    with urllib.request.urlopen(SECOM_URL, timeout=120) as response:
        archive = zipfile.ZipFile(io.BytesIO(response.read()))
    return np.genfromtxt(io.BytesIO(archive.read("secom.data")), delimiter=" ")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--secom-data", type=Path, default=None, help="Local copy of secom.data.")
    parser.add_argument("--scaler", type=Path, default=DEFAULT_SCALER, help="scaler_params.json used in training.")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    raw = load_raw(args.secom_data)
    if raw.ndim != 2:
        raise SystemExit(f"Unexpected SECOM shape: {raw.shape}")

    missing = np.isnan(raw).mean(axis=0)
    kept = np.where(missing <= MAX_MISSING_FRACTION)[0]

    if args.scaler.exists():
        scaler = json.loads(args.scaler.read_text(encoding="utf-8"))
        expected = int(scaler["n_features_in"])
        if kept.size != expected:
            raise SystemExit(
                f"Missing-value rule kept {kept.size} columns but the scaler expects {expected}."
            )
        # The scaler was fit on the training split, so means differ slightly; a gross
        # mismatch would mean the column selection is wrong.
        scaler_mean = np.asarray(scaler["mean"])
        column_mean = np.nanmean(raw[:, kept], axis=0)
        relative = np.abs(column_mean - scaler_mean) / (np.abs(scaler_mean) + 1e-9)
        print(f"Column alignment: median relative mean error {np.median(relative):.2e}")
        if np.median(relative) > 0.05:
            raise SystemExit("Column selection does not line up with the training scaler.")
    else:
        print(f"Scaler not found at {args.scaler}; skipping alignment check.")

    minimum = np.nanmin(raw[:, kept], axis=0)
    maximum = np.nanmax(raw[:, kept], axis=0)
    # Constant columns collapse to 0 under min-max, so any positive range restores them.
    span = np.where(maximum > minimum, maximum - minimum, 1.0)

    def render(values: np.ndarray) -> str:
        items = [repr(float(value)) for value in values]
        lines: list[str] = []
        current = "  "
        for item in items:
            entry = f"{item}, "
            if len(current) + len(entry) > 110:
                lines.append(current.rstrip())
                current = "  "
            current += entry
        lines.append(current.rstrip())
        return "\n".join(lines)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        "// AUTO-GENERATED by scripts/export_feature_space.py — do not edit by hand.\n"
        f"// Derived from the UCI SECOM release: columns with more than "
        f"{MAX_MISSING_FRACTION:.0%} missing values are dropped.\n\n"
        "/** Indices into the 590-column replay CSV that the model consumes, in model order. */\n"
        f"export const MODEL_COLUMN_INDICES: readonly number[] = [\n{render(kept)}\n];\n\n"
        "/** Per-column minimum of the raw dataset, used to undo the CSV's min-max normalization. */\n"
        f"export const COLUMN_MIN: readonly number[] = [\n{render(minimum)}\n];\n\n"
        "/** Per-column (max - min) of the raw dataset; 1 for columns that are constant. */\n"
        f"export const COLUMN_RANGE: readonly number[] = [\n{render(span)}\n];\n",
        encoding="utf-8",
    )

    print(f"Wrote {args.output} ({args.output.stat().st_size / 1024:.0f} KB)")
    print(f"  kept columns: {kept.size} of {raw.shape[1]}")
    print(f"  dropped:      {sorted(set(range(raw.shape[1])) - set(kept.tolist()))}")


if __name__ == "__main__":
    main()
